# Generated by Django 3.1.1 on 2020-09-15 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('p4_api', '0004_auto_20200915_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='added',
        ),
        migrations.RemoveField(
            model_name='game',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
