# Generated by Django 3.1.1 on 2020-09-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p4_api', '0007_auto_20200916_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
