# Generated by Django 3.1.1 on 2020-11-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p4_api', '0010_auto_20201110_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
    ]
