# Generated by Django 3.1.1 on 2020-11-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('p4_api', '0012_game_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name_plural': 'games'},
        ),
        migrations.AlterField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='p4_api.category'),
        ),
    ]
