# Generated by Django 3.1.1 on 2020-11-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p4_api', '0013_auto_20201110_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='added',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
