# Generated by Django 3.1.1 on 2020-11-12 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p4_api', '0015_category_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='created_at',
            new_name='added',
        ),
        migrations.RemoveField(
            model_name='game',
            name='updated_at',
        ),
    ]
