# Generated by Django 3.1.1 on 2020-11-12 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p4_api', '0016_auto_20201112_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='p4_api.category'),
        ),
    ]
